export const LOCALIZATION = {
  en: {
    home: "Home",
    goals: "Goals",
    insights: "Insights",
    profile: "Profile",
    netWorth: "Net worth",
    thisMonth: "this month",
    income: "Income",
    expenses: "Expenses",
    balance: "Balance",
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    quickActions: "Quick actions",
    recent: "Recent",
    activeGoals: "Active goals",
    longestStreak: "Longest streak",
    totalSaved: "Total saved",
    emiTracker: "EMI Tracker",
    monthlyBudget: "Monthly Budget",
    financialHealth: "Financial Health",
    addTransaction: "Add Transaction",
    addGoal: "Add Goal",
    addEMI: "Add EMI",
    settings: "Settings",
    appearance: "Appearance",
    language: "Language",
    edition: "Edition",
  },
  hi: {
    home: "मुख्य",
    goals: "लक्ष्य",
    insights: "अन्तर्दृष्टि",
    profile: "प्रोफ़ाइल",
    netWorth: "कुल संपत्ति",
    thisMonth: "इस महीने",
    income: "आय",
    expenses: "खर्च",
    balance: "बैलेंस",
    greeting_morning: "शुभ प्रभात",
    greeting_afternoon: "नमस्कार",
    greeting_evening: "शुभ संध्या",
    quickActions: "त्वरित कार्रवाई",
    recent: "हाल के",
    activeGoals: "सक्रिय लक्ष्य",
    longestStreak: "सबसे लंबी स्ट्रीक",
    totalSaved: "कुल बचत",
    emiTracker: "EMI ट्रैकर",
    monthlyBudget: "मासिक बजट",
    financialHealth: "वित्तीय स्वास्थ्य",
    addTransaction: "लेनदेन जोड़ें",
    addGoal: "लक्ष्य जोड़ें",
    addEMI: "EMI जोड़ें",
    settings: "सेटिंग्स",
    appearance: "दिखावट",
    language: "भाषा",
    edition: "संस्करण",
  },
};

export type LanguageCode = keyof typeof LOCALIZATION;
export type LocalizationKey = keyof typeof LOCALIZATION["en"];
